apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: demo-voting-app
    name: postgrees-service
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app
  ports:
     - port: 5432
       targetPort: 5432
  type: ClusterIP