apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: demo-voting-app
    name: result-app-service
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  ports:
     - port: 80
       targetPort: 80
       nodeport: 30008
  type: NodePort