apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: demo-voting-app
    name: voting-app-service
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
     - port: 80
       targetPort: 80
       nodeport: 30004
  type: NodePort